; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
upload_speed = 921600
monitor_speed = 115200
upload_protocol = esptool

lib_deps = madhephaestus/ESP32Servo@^3.2.1, lovyan03/LovyanGFX@^1.2.24, robtillaart/AS5600@^0.6.7, adafruit/Adafruit NeoPixel

; === Force C++17 ===
build_flags = 
    -std=gnu++17
    -std=gnu11

build_unflags = 
    -std=gnu++11
    -std=gnu++14
    